name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v1
      with:
        arguments: --warning-mode all
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: core/build/libs/
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1.1
      with:
        files: core/build/test-results/test/*.xml
